---
- name: Zip and Copy the files to local machine
  hosts: node2
  become: yes
  vars:
    Files: []     #Initializing list to debug and identify files to zip
  roles:
    - /home/vagrant/findfetch_role #Used for testing and dryrun on local machine
    #- /home/{{ ansible_user_id }}/findfetch_role ----->Syntax to run on anyserver
