---
# tasks file for findfetch_role
  - name: Search all the files in the source dir/subdir
    find:
      paths: "{{ src_file_loc }}"  #Retreiving file/folder path from variable file
      age: -30d
      recurse: yes
      excludes: "*.log,*.out"
    register: files_to_zip  #Gather selected files

  - name: Adding Files to the LIST
    set_fact:
      Files: "{{ Files + [item.path]}}" #Adding files to LIST which are to be zipped
    with_items: "{{ files_to_zip.files }}"

  - debug:
      var: Files #Show files from LIST

  - name: Archive selected files
    archive:
      path: "{{ item.path }}"
      dest: "{{ src_file_loc }}/bkpfiles.zip" #Zip selected files from the LIST
      format: zip
    with_items: "{{ files_to_zip.files }}"

  - name: Fetch files from remote host to local host
    fetch:
      src: "{{ src_file_loc }}/bkpfiles.zip"
      dest: "{{ dest_file_loc }}/bkpfiles.zip"
      flat: yes                 #To avoid creating directory structure on the target
    register: fetch_opt

  - debug:
      var: fetch_opt

  - name: Delete Zip file in Source
    file:
      path: "{{ src_file_loc }}/bkpfiles.zip"
      state: absent
    tags: delete_zip #If required we can delete zip file manually using ansible tags
